### ISSUE TITLE
Question: Only Validation?

### ISSUE THREAD

**Issue by johannesschobel** [mike-north/jsonapi-typescript#60]
This is rather a question, than a bug report or feature request. I just want to be sure to get the purpose of this lib proprely.

This library is purely for **validating** the proper structure of an `JSON:API` conform document, right? It is **not** for transforming entities into JSON:API conform structures?

**Comment by mike-north** [comment]
This library provides type information for describing JSON:API documents and parts of documents. It compiles to zero javascript code, and thus contains nothing that could transform anything.

**Comment by johannesschobel** [comment]
Dear @mike-north ,
thanks for clarifying my initial question! all the best
